program: ./src/learn/train_roberta.sh
project: critical-period
method: bayes
metric:
  goal: minimize
  name: eval/loss
parameters:
  gradient_accumulation_steps:
    values: [64, 128, 256, 512]
  learning_rate:
    distribution: log_uniform_values
    min: 10e-5
    max: 10e-3
  mlm_probability:
    values: [0.15, 0.3, 0.4, 0.5]
  warmup_ratio:
    values: [0.05, 0.06, 0.07, 0.08, 0.09, 0.1]
early_terminate:
  type: hyperband
  min_iter: 5
  eta: 2
command:
  - ${env}
  - bash
  - ${program}
  - "--evaluation_strategy steps"
  - "--eval_steps 0.02"
  - "--max_eval_samples 50000"
  - ${args}
